# Copyright Datum Technology Corporation
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
########################################################################################################################

# This file contains the built-in Moore.io CLI Client default configuration parameters
# You can override these in your user config (~/mio.toml) or project config ($PROJECT_ROOT/mio.toml)


[ip]
paths = ["rtl", "dv", "tools"]

[simulation]
root-path        = "sim"
output-dir       = "out"
results-dir      = "results"
history-filename = "history.yml"
test-result-path-template = "{{ ip_name }}_{{ test_name }}_{{ seed }}"

[lint]
root-path = "lint"

[synthesis]
root-path = "syn"
